// Contract addresses — auto-generated by scripts/sync-deployments.ts
// Do not edit manually. Run: pnpm sync:deployments

export const AZETH_CONTRACTS = {
  baseSepolia: {
    factory: '0x83f780Dc2367A1F62134f70b3e454bC5de8030e5' as `0x${string}`,
    guardianModule: '0xD45b1653a1BcFd5b0B1bD8b6d46670a0DCeDb318' as `0x${string}`,
    trustRegistryModule: '0xe4d53d9576a13b44751C7767e747f886FaC8FFa0' as `0x${string}`,
    paymentAgreementModule: '0x582A4A19D9F9F9ed0521B30F53352A6DA9F38419' as `0x${string}`,
    reputationModule: '0xd68B76Bdf8E95387208A713b8b40414CB4f36CE6' as `0x${string}`,
    priceOracle: '0xA525109A04CbC7A61Bf55b3da0f76093cC7B5492' as `0x${string}`,
    accountImplementation: '0x75968416F4200D8FB2276d5aA3b385De9C95AfFf' as `0x${string}`,
    trustL2Reader: '' as `0x${string}`,
  },
  ethereumSepolia: {
    factory: '0x83f780Dc2367A1F62134f70b3e454bC5de8030e5' as `0x${string}`,
    guardianModule: '0xD45b1653a1BcFd5b0B1bD8b6d46670a0DCeDb318' as `0x${string}`,
    trustRegistryModule: '0xe4d53d9576a13b44751C7767e747f886FaC8FFa0' as `0x${string}`,
    paymentAgreementModule: '0x582A4A19D9F9F9ed0521B30F53352A6DA9F38419' as `0x${string}`,
    reputationModule: '0xd68B76Bdf8E95387208A713b8b40414CB4f36CE6' as `0x${string}`,
    priceOracle: '0xA525109A04CbC7A61Bf55b3da0f76093cC7B5492' as `0x${string}`,
    accountImplementation: '0x75968416F4200D8FB2276d5aA3b385De9C95AfFf' as `0x${string}`,
    trustL2Reader: '0xf53F234Bf12D113D420d6D6ba96b2FA78aeD889E' as `0x${string}`,
  },
  base: {
    factory: '' as `0x${string}`,
    guardianModule: '' as `0x${string}`,
    trustRegistryModule: '' as `0x${string}`,
    paymentAgreementModule: '' as `0x${string}`,
    reputationModule: '' as `0x${string}`,
    priceOracle: '' as `0x${string}`,
    accountImplementation: '' as `0x${string}`,
    trustL2Reader: '' as `0x${string}`,
  },
  ethereum: {
    factory: '' as `0x${string}`,
    guardianModule: '' as `0x${string}`,
    trustRegistryModule: '' as `0x${string}`,
    paymentAgreementModule: '' as `0x${string}`,
    reputationModule: '' as `0x${string}`,
    priceOracle: '' as `0x${string}`,
    accountImplementation: '' as `0x${string}`,
    trustL2Reader: '' as `0x${string}`,
  },
} as const;

// External contracts — ERC-8004 Identity Registry
export const ERC8004_REGISTRY = {
  base: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432' as `0x${string}`,
  ethereum: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432' as `0x${string}`,
  baseSepolia: '0x8004A818BFB912233c491871b3d84c89A494BD9e' as `0x${string}`,
  ethereumSepolia: '0x8004A818BFB912233c491871b3d84c89A494BD9e' as `0x${string}`,
} as const;

// External contracts — ERC-8004 Reputation Registry
export const ERC8004_REPUTATION_REGISTRY = {
  base: '0x8004BAa17C55a88189AE136b182e5fdA19dE9b63' as `0x${string}`,
  ethereum: '0x8004BAa17C55a88189AE136b182e5fdA19dE9b63' as `0x${string}`,
  baseSepolia: '0x8004B663056A597Dffe9eCcC1965A193B7388713' as `0x${string}`,
  ethereumSepolia: '0x8004B663056A597Dffe9eCcC1965A193B7388713' as `0x${string}`,
} as const;

export const ENTRYPOINT_V07 = '0x0000000071727De22E5E9d8BAf0edAc6f37da032' as `0x${string}`;
