// Contract addresses — auto-generated by scripts/sync-deployments.ts
// Do not edit manually. Run: pnpm sync:deployments

export const AZETH_CONTRACTS = {
  baseSepolia: {
    factory: '0x28e808DD688F722631482C276488289a6A8ea3e3' as `0x${string}`,
    guardianModule: '0xC12043Ba3D58e5959E683bfFf8D94e21C8C6533C' as `0x${string}`,
    trustRegistryModule: '0x9A199eeFFd9A4837556139474eaf8420B6ED71bD' as `0x${string}`,
    paymentAgreementModule: '0xa3e51F13CF6B74170f8Bb6CcA2c2835563179C89' as `0x${string}`,
    reputationModule: '0xB8C98ace6bdB25f5AEb2031150A5944F3135ccC0' as `0x${string}`,
    priceOracle: '0x64Da6aEbE4121CE9CE8145d97950495A45BB72be' as `0x${string}`,
    accountImplementation: '0xCEEf6Aff7f08b9902198203E2F1a07A2b10885AD' as `0x${string}`,
  },
  ethereumSepolia: {
    factory: '0x28e808DD688F722631482C276488289a6A8ea3e3' as `0x${string}`,
    guardianModule: '0xC12043Ba3D58e5959E683bfFf8D94e21C8C6533C' as `0x${string}`,
    trustRegistryModule: '0x9A199eeFFd9A4837556139474eaf8420B6ED71bD' as `0x${string}`,
    paymentAgreementModule: '0xa3e51F13CF6B74170f8Bb6CcA2c2835563179C89' as `0x${string}`,
    reputationModule: '0xB8C98ace6bdB25f5AEb2031150A5944F3135ccC0' as `0x${string}`,
    priceOracle: '0x64Da6aEbE4121CE9CE8145d97950495A45BB72be' as `0x${string}`,
    accountImplementation: '0xCEEf6Aff7f08b9902198203E2F1a07A2b10885AD' as `0x${string}`,
  },
  base: {
    factory: '' as `0x${string}`,
    guardianModule: '' as `0x${string}`,
    trustRegistryModule: '' as `0x${string}`,
    paymentAgreementModule: '' as `0x${string}`,
    reputationModule: '' as `0x${string}`,
    priceOracle: '' as `0x${string}`,
    accountImplementation: '' as `0x${string}`,
  },
  ethereum: {
    factory: '' as `0x${string}`,
    guardianModule: '' as `0x${string}`,
    trustRegistryModule: '' as `0x${string}`,
    paymentAgreementModule: '' as `0x${string}`,
    reputationModule: '' as `0x${string}`,
    priceOracle: '' as `0x${string}`,
    accountImplementation: '' as `0x${string}`,
  },
} as const;

// External contracts — ERC-8004 Identity Registry
export const ERC8004_REGISTRY = {
  base: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432' as `0x${string}`,
  ethereum: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432' as `0x${string}`,
  baseSepolia: '0x8004A818BFB912233c491871b3d84c89A494BD9e' as `0x${string}`,
  ethereumSepolia: '0x8004A818BFB912233c491871b3d84c89A494BD9e' as `0x${string}`,
} as const;

// External contracts — ERC-8004 Reputation Registry
export const ERC8004_REPUTATION_REGISTRY = {
  base: '0x8004BAa17C55a88189AE136b182e5fdA19dE9b63' as `0x${string}`,
  ethereum: '0x8004BAa17C55a88189AE136b182e5fdA19dE9b63' as `0x${string}`,
  baseSepolia: '0x8004B663056A597Dffe9eCcC1965A193B7388713' as `0x${string}`,
  ethereumSepolia: '0x8004B663056A597Dffe9eCcC1965A193B7388713' as `0x${string}`,
} as const;

export const ENTRYPOINT_V07 = '0x0000000071727De22E5E9d8BAf0edAc6f37da032' as `0x${string}`;
